services:
  web-frontend-prod:
    container_name: akkasgroup-web-frontend-prod

    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        WP_GRAPHQL_ENDPOINT: ${WP_GRAPHQL_BUILD_ENDPOINT}

    restart: unless-stopped

    ports:
      - "9071:3000"

    env_file:
      - .env.prod

    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0

    networks:
      - default
      - cms-akkasgroup-network

networks:
  cms-akkasgroup-network:
    external: true
    name: cms-akkasgroup-network
